excerpt_separator: <!--more-->
host: 0.0.0.0
name: ITJunta
description: Мікроблог для всякої єрунди.
url: https://nyurch.github.io
paginate: 10
paginate_path: /blog/page:num/
plugins:
  - jekyll-feed
  - jekyll-paginate
# Disqus Comments
disqus:
 # Leave shortname blank to disable comments site-wide.
 # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
 shortname: nyurch-github-io

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
